import type { DeptConfig } from "@/types/department.types";

export const DEPT_CONFIG: DeptConfig[] = [
  {
    slug: "marketing",
    name: "Marketing",
    colorHex: "#8b5cf6",
    icon: "Megaphone",
    kpis: [
      {
        key: "campaign_spend",
        label: "Campaign Spend",
        unit: "currency",
        defaultTarget: 50000,
        warningThreshold: 0.5,
        criticalThreshold: 0.2,
        weight: 0.15,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "currency",
        description: "Total spend across all campaigns today",
      },
      {
        key: "leads_generated",
        label: "Leads Generated",
        unit: "count",
        defaultTarget: 50,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.4,
        isBottleneckKpi: true,
        linkedTo: { dept: "sales", kpi: "leads_capacity" },
        aggregation: "sum",
        inputType: "number",
        description: "Total new leads captured today",
      },
      {
        key: "cost_per_lead",
        label: "Cost Per Lead",
        unit: "currency",
        defaultTarget: 25,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.2,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "currency",
        description: "Average cost to acquire one lead",
      },
      {
        key: "conversion_rate",
        label: "Lead Conversion Rate",
        unit: "percentage",
        defaultTarget: 5,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "percentage",
        description: "% of leads that convert to customers",
      },
    ],
  },
  {
    slug: "sales",
    name: "Sales",
    colorHex: "#10b981",
    icon: "TrendingUp",
    kpis: [
      {
        key: "calls_completed",
        label: "Calls Completed",
        unit: "count",
        defaultTarget: 30,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.2,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "leads_capacity",
        label: "Lead Processing Capacity",
        unit: "count",
        defaultTarget: 50,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.1,
        isBottleneckKpi: true,
        aggregation: "sum",
        inputType: "number",
        description: "Max leads the team can process per day",
      },
      {
        key: "deals_closed",
        label: "Deals Closed",
        unit: "count",
        defaultTarget: 5,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.3,
        isBottleneckKpi: true,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "revenue_generated",
        label: "Revenue Generated",
        unit: "currency",
        defaultTarget: 25000,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.3,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "currency",
      },
      {
        key: "pipeline_value",
        label: "Pipeline Value",
        unit: "currency",
        defaultTarget: 500000,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.1,
        isBottleneckKpi: false,
        aggregation: "last",
        inputType: "currency",
        description: "Total value of active deals in pipeline",
      },
    ],
  },
  {
    slug: "hr",
    name: "Human Resources",
    colorHex: "#f59e0b",
    icon: "Users",
    kpis: [
      {
        key: "open_positions",
        label: "Open Positions",
        unit: "count",
        defaultTarget: 0,
        warningThreshold: 0.5,
        criticalThreshold: 0.2,
        weight: 0.3,
        isBottleneckKpi: true,
        aggregation: "last",
        inputType: "number",
        description: "Positions open for more than 30 days",
      },
      {
        key: "interviews_conducted",
        label: "Interviews Conducted",
        unit: "count",
        defaultTarget: 5,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "offers_sent",
        label: "Offers Sent",
        unit: "count",
        defaultTarget: 2,
        warningThreshold: 0.5,
        criticalThreshold: 0.2,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "new_hires",
        label: "New Hires",
        unit: "count",
        defaultTarget: 1,
        warningThreshold: 0.5,
        criticalThreshold: 0.0,
        weight: 0.2,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
    ],
  },
  {
    slug: "operations",
    name: "Operations",
    colorHex: "#3b82f6",
    icon: "Settings",
    kpis: [
      {
        key: "projects_delivered",
        label: "Projects Delivered",
        unit: "count",
        defaultTarget: 10,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.35,
        isBottleneckKpi: true,
        linkedTo: { dept: "sales", kpi: "deals_closed" },
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "avg_delivery_days",
        label: "Avg. Delivery Time",
        unit: "days",
        defaultTarget: 5,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "number",
        description: "Average days to deliver a project",
      },
      {
        key: "delayed_projects",
        label: "Delayed Projects",
        unit: "count",
        defaultTarget: 0,
        warningThreshold: 0.5,
        criticalThreshold: 0.2,
        weight: 0.25,
        isBottleneckKpi: true,
        aggregation: "last",
        inputType: "number",
      },
      {
        key: "team_utilization",
        label: "Team Utilization",
        unit: "percentage",
        defaultTarget: 80,
        warningThreshold: 0.75,
        criticalThreshold: 0.5,
        weight: 0.15,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "percentage",
      },
    ],
  },
  {
    slug: "finance",
    name: "Finance",
    colorHex: "#ef4444",
    icon: "DollarSign",
    kpis: [
      {
        key: "cash_balance",
        label: "Cash Balance",
        unit: "currency",
        defaultTarget: 500000,
        warningThreshold: 0.5,
        criticalThreshold: 0.25,
        weight: 0.3,
        isBottleneckKpi: false,
        aggregation: "last",
        inputType: "currency",
      },
      {
        key: "monthly_expenses",
        label: "Monthly Expenses",
        unit: "currency",
        defaultTarget: 100000,
        warningThreshold: 0.8,
        criticalThreshold: 0.9,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "currency",
      },
      {
        key: "monthly_revenue",
        label: "Monthly Revenue",
        unit: "currency",
        defaultTarget: 150000,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.3,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "currency",
      },
      {
        key: "burn_rate",
        label: "Monthly Burn Rate",
        unit: "currency",
        defaultTarget: 50000,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.15,
        isBottleneckKpi: false,
        aggregation: "last",
        inputType: "currency",
        description: "Net cash consumed per month",
      },
    ],
  },
  {
    slug: "product",
    name: "Product",
    colorHex: "#ec4899",
    icon: "Package",
    kpis: [
      {
        key: "features_shipped",
        label: "Features Shipped",
        unit: "count",
        defaultTarget: 3,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.35,
        isBottleneckKpi: true,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "bugs_closed",
        label: "Bugs Closed",
        unit: "count",
        defaultTarget: 10,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "sprint_completion",
        label: "Sprint Completion Rate",
        unit: "percentage",
        defaultTarget: 85,
        warningThreshold: 0.7,
        criticalThreshold: 0.5,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "percentage",
      },
      {
        key: "nps_score",
        label: "NPS Score",
        unit: "count",
        defaultTarget: 50,
        warningThreshold: 0.6,
        criticalThreshold: 0.3,
        weight: 0.15,
        isBottleneckKpi: false,
        aggregation: "last",
        inputType: "number",
        description: "Net Promoter Score (-100 to 100)",
      },
    ],
  },
  {
    slug: "customer_success",
    name: "Customer Success",
    colorHex: "#14b8a6",
    icon: "HeartHandshake",
    kpis: [
      {
        key: "tickets_handled",
        label: "Tickets Handled",
        unit: "count",
        defaultTarget: 50,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.25,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "csat_score",
        label: "Customer Satisfaction",
        unit: "percentage",
        defaultTarget: 90,
        warningThreshold: 0.8,
        criticalThreshold: 0.6,
        weight: 0.3,
        isBottleneckKpi: false,
        aggregation: "avg",
        inputType: "percentage",
        description: "CSAT score as percentage",
      },
      {
        key: "churn_count",
        label: "Churn This Month",
        unit: "count",
        defaultTarget: 0,
        warningThreshold: 0.5,
        criticalThreshold: 0.2,
        weight: 0.3,
        isBottleneckKpi: true,
        aggregation: "sum",
        inputType: "number",
      },
      {
        key: "renewals",
        label: "Renewals This Month",
        unit: "count",
        defaultTarget: 10,
        warningThreshold: 0.7,
        criticalThreshold: 0.4,
        weight: 0.15,
        isBottleneckKpi: false,
        aggregation: "sum",
        inputType: "number",
      },
    ],
  },
];

export function getDeptConfig(slug: string): DeptConfig | undefined {
  return DEPT_CONFIG.find((d) => d.slug === slug.toLowerCase());
}
